from cards import make_deck
from question_5 import deck_suits


def test_q5_deck_suits_1():
    expected = [[(2, 'Clubs', '2 of Clubs', ' 2C'),
                (3, 'Clubs', '3 of Clubs', ' 3C'),
                (4, 'Clubs', '4 of Clubs', ' 4C'),
                (5, 'Clubs', '5 of Clubs', ' 5C'),
                (6, 'Clubs', '6 of Clubs', ' 6C'),
                (7, 'Clubs', '7 of Clubs', ' 7C'),
                (8, 'Clubs', '8 of Clubs', ' 8C'),
                (9, 'Clubs', '9 of Clubs', ' 9C'),
                (10, 'Clubs', '10 of Clubs', '10C'),
                (11, 'Clubs', 'Jack of Clubs', ' JC'),
                (12, 'Clubs', 'Queen of Clubs', ' QC'),
                (13, 'Clubs', 'King of Clubs', ' KC'),
                (14, 'Clubs', 'Ace of Clubs', ' AC')],
                [(2, 'Diamonds', '2 of Diamonds', ' 2D'),
                (3, 'Diamonds', '3 of Diamonds', ' 3D'),
                (4, 'Diamonds', '4 of Diamonds', ' 4D'),
                (5, 'Diamonds', '5 of Diamonds', ' 5D'),
                (6, 'Diamonds', '6 of Diamonds', ' 6D'),
                (7, 'Diamonds', '7 of Diamonds', ' 7D'),
                (8, 'Diamonds', '8 of Diamonds', ' 8D'),
                (9, 'Diamonds', '9 of Diamonds', ' 9D'),
                (10, 'Diamonds', '10 of Diamonds', '10D'),
                (11, 'Diamonds', 'Jack of Diamonds', ' JD'),
                (12, 'Diamonds', 'Queen of Diamonds', ' QD'),
                (13, 'Diamonds', 'King of Diamonds', ' KD'),
                (14, 'Diamonds', 'Ace of Diamonds', ' AD')],
                [(2, 'Hearts', '2 of Hearts', ' 2H'),
                (3, 'Hearts', '3 of Hearts', ' 3H'),
                (4, 'Hearts', '4 of Hearts', ' 4H'),
                (5, 'Hearts', '5 of Hearts', ' 5H'),
                (6, 'Hearts', '6 of Hearts', ' 6H'),
                (7, 'Hearts', '7 of Hearts', ' 7H'),
                (8, 'Hearts', '8 of Hearts', ' 8H'),
                (9, 'Hearts', '9 of Hearts', ' 9H'),
                (10, 'Hearts', '10 of Hearts', '10H'),
                (11, 'Hearts', 'Jack of Hearts', ' JH'),
                (12, 'Hearts', 'Queen of Hearts', ' QH'),
                (13, 'Hearts', 'King of Hearts', ' KH'),
                (14, 'Hearts', 'Ace of Hearts', ' AH')],
                [(2, 'Spades', '2 of Spades', ' 2S'),
                 (3, 'Spades', '3 of Spades', ' 3S'),
                 (4, 'Spades', '4 of Spades', ' 4S'),
                 (5, 'Spades', '5 of Spades', ' 5S'),
                 (6, 'Spades', '6 of Spades', ' 6S'),
                 (7, 'Spades', '7 of Spades', ' 7S'),
                 (8, 'Spades', '8 of Spades', ' 8S'),
                 (9, 'Spades', '9 of Spades', ' 9S'),
                 (10, 'Spades', '10 of Spades', '10S'),
                 (11, 'Spades', 'Jack of Spades', ' JS'),
                 (12, 'Spades', 'Queen of Spades', ' QS'),
                 (13, 'Spades', 'King of Spades', ' KS'),
                 (14, 'Spades', 'Ace of Spades', ' AS')]]
    actual = deck_suits(make_deck(shuffle_deck=True))
    assert actual == expected
